/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductsTrustkeyUsbTokenRouteImport } from './routes/products.trustkey-usb-token'
import { Route as ProductsSafenet5100UsbTokenRouteImport } from './routes/products.safenet-5100-usb-token'
import { Route as ProductsProxkeyUsbTokenRouteImport } from './routes/products.proxkey-usb-token'
import { Route as ProductsMtokenUsbTokenRouteImport } from './routes/products.mtoken-usb-token'
import { Route as ProductsForeignNationalDscRouteImport } from './routes/products.foreign-national-dsc'
import { Route as ProductsEpass2003UsbTokenRouteImport } from './routes/products.epass-2003-usb-token'
import { Route as ProductsDgftDscRouteImport } from './routes/products.dgft-dsc'
import { Route as ProductsClass3OrganizationDscRouteImport } from './routes/products.class-3-organization-dsc'
import { Route as ProductsClass3IndividualDscRouteImport } from './routes/products.class-3-individual-dsc'
import { Route as ProductsClass3ComboDscRouteImport } from './routes/products.class-3-combo-dsc'

const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsTrustkeyUsbTokenRoute =
  ProductsTrustkeyUsbTokenRouteImport.update({
    id: '/trustkey-usb-token',
    path: '/trustkey-usb-token',
    getParentRoute: () => ProductsRoute,
  } as any)
const ProductsSafenet5100UsbTokenRoute =
  ProductsSafenet5100UsbTokenRouteImport.update({
    id: '/safenet-5100-usb-token',
    path: '/safenet-5100-usb-token',
    getParentRoute: () => ProductsRoute,
  } as any)
const ProductsProxkeyUsbTokenRoute = ProductsProxkeyUsbTokenRouteImport.update({
  id: '/proxkey-usb-token',
  path: '/proxkey-usb-token',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsMtokenUsbTokenRoute = ProductsMtokenUsbTokenRouteImport.update({
  id: '/mtoken-usb-token',
  path: '/mtoken-usb-token',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsForeignNationalDscRoute =
  ProductsForeignNationalDscRouteImport.update({
    id: '/foreign-national-dsc',
    path: '/foreign-national-dsc',
    getParentRoute: () => ProductsRoute,
  } as any)
const ProductsEpass2003UsbTokenRoute =
  ProductsEpass2003UsbTokenRouteImport.update({
    id: '/epass-2003-usb-token',
    path: '/epass-2003-usb-token',
    getParentRoute: () => ProductsRoute,
  } as any)
const ProductsDgftDscRoute = ProductsDgftDscRouteImport.update({
  id: '/dgft-dsc',
  path: '/dgft-dsc',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsClass3OrganizationDscRoute =
  ProductsClass3OrganizationDscRouteImport.update({
    id: '/class-3-organization-dsc',
    path: '/class-3-organization-dsc',
    getParentRoute: () => ProductsRoute,
  } as any)
const ProductsClass3IndividualDscRoute =
  ProductsClass3IndividualDscRouteImport.update({
    id: '/class-3-individual-dsc',
    path: '/class-3-individual-dsc',
    getParentRoute: () => ProductsRoute,
  } as any)
const ProductsClass3ComboDscRoute = ProductsClass3ComboDscRouteImport.update({
  id: '/class-3-combo-dsc',
  path: '/class-3-combo-dsc',
  getParentRoute: () => ProductsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/downloads': typeof DownloadsRoute
  '/partners': typeof PartnersRoute
  '/pricing': typeof PricingRoute
  '/products': typeof ProductsRouteWithChildren
  '/products/class-3-combo-dsc': typeof ProductsClass3ComboDscRoute
  '/products/class-3-individual-dsc': typeof ProductsClass3IndividualDscRoute
  '/products/class-3-organization-dsc': typeof ProductsClass3OrganizationDscRoute
  '/products/dgft-dsc': typeof ProductsDgftDscRoute
  '/products/epass-2003-usb-token': typeof ProductsEpass2003UsbTokenRoute
  '/products/foreign-national-dsc': typeof ProductsForeignNationalDscRoute
  '/products/mtoken-usb-token': typeof ProductsMtokenUsbTokenRoute
  '/products/proxkey-usb-token': typeof ProductsProxkeyUsbTokenRoute
  '/products/safenet-5100-usb-token': typeof ProductsSafenet5100UsbTokenRoute
  '/products/trustkey-usb-token': typeof ProductsTrustkeyUsbTokenRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/downloads': typeof DownloadsRoute
  '/partners': typeof PartnersRoute
  '/pricing': typeof PricingRoute
  '/products/class-3-combo-dsc': typeof ProductsClass3ComboDscRoute
  '/products/class-3-individual-dsc': typeof ProductsClass3IndividualDscRoute
  '/products/class-3-organization-dsc': typeof ProductsClass3OrganizationDscRoute
  '/products/dgft-dsc': typeof ProductsDgftDscRoute
  '/products/epass-2003-usb-token': typeof ProductsEpass2003UsbTokenRoute
  '/products/foreign-national-dsc': typeof ProductsForeignNationalDscRoute
  '/products/mtoken-usb-token': typeof ProductsMtokenUsbTokenRoute
  '/products/proxkey-usb-token': typeof ProductsProxkeyUsbTokenRoute
  '/products/safenet-5100-usb-token': typeof ProductsSafenet5100UsbTokenRoute
  '/products/trustkey-usb-token': typeof ProductsTrustkeyUsbTokenRoute
  '/products': typeof ProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/downloads': typeof DownloadsRoute
  '/partners': typeof PartnersRoute
  '/pricing': typeof PricingRoute
  '/products': typeof ProductsRouteWithChildren
  '/products/class-3-combo-dsc': typeof ProductsClass3ComboDscRoute
  '/products/class-3-individual-dsc': typeof ProductsClass3IndividualDscRoute
  '/products/class-3-organization-dsc': typeof ProductsClass3OrganizationDscRoute
  '/products/dgft-dsc': typeof ProductsDgftDscRoute
  '/products/epass-2003-usb-token': typeof ProductsEpass2003UsbTokenRoute
  '/products/foreign-national-dsc': typeof ProductsForeignNationalDscRoute
  '/products/mtoken-usb-token': typeof ProductsMtokenUsbTokenRoute
  '/products/proxkey-usb-token': typeof ProductsProxkeyUsbTokenRoute
  '/products/safenet-5100-usb-token': typeof ProductsSafenet5100UsbTokenRoute
  '/products/trustkey-usb-token': typeof ProductsTrustkeyUsbTokenRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/dashboard'
    | '/downloads'
    | '/partners'
    | '/pricing'
    | '/products'
    | '/products/class-3-combo-dsc'
    | '/products/class-3-individual-dsc'
    | '/products/class-3-organization-dsc'
    | '/products/dgft-dsc'
    | '/products/epass-2003-usb-token'
    | '/products/foreign-national-dsc'
    | '/products/mtoken-usb-token'
    | '/products/proxkey-usb-token'
    | '/products/safenet-5100-usb-token'
    | '/products/trustkey-usb-token'
    | '/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/dashboard'
    | '/downloads'
    | '/partners'
    | '/pricing'
    | '/products/class-3-combo-dsc'
    | '/products/class-3-individual-dsc'
    | '/products/class-3-organization-dsc'
    | '/products/dgft-dsc'
    | '/products/epass-2003-usb-token'
    | '/products/foreign-national-dsc'
    | '/products/mtoken-usb-token'
    | '/products/proxkey-usb-token'
    | '/products/safenet-5100-usb-token'
    | '/products/trustkey-usb-token'
    | '/products'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/dashboard'
    | '/downloads'
    | '/partners'
    | '/pricing'
    | '/products'
    | '/products/class-3-combo-dsc'
    | '/products/class-3-individual-dsc'
    | '/products/class-3-organization-dsc'
    | '/products/dgft-dsc'
    | '/products/epass-2003-usb-token'
    | '/products/foreign-national-dsc'
    | '/products/mtoken-usb-token'
    | '/products/proxkey-usb-token'
    | '/products/safenet-5100-usb-token'
    | '/products/trustkey-usb-token'
    | '/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  DownloadsRoute: typeof DownloadsRoute
  PartnersRoute: typeof PartnersRoute
  PricingRoute: typeof PricingRoute
  ProductsRoute: typeof ProductsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/trustkey-usb-token': {
      id: '/products/trustkey-usb-token'
      path: '/trustkey-usb-token'
      fullPath: '/products/trustkey-usb-token'
      preLoaderRoute: typeof ProductsTrustkeyUsbTokenRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/safenet-5100-usb-token': {
      id: '/products/safenet-5100-usb-token'
      path: '/safenet-5100-usb-token'
      fullPath: '/products/safenet-5100-usb-token'
      preLoaderRoute: typeof ProductsSafenet5100UsbTokenRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/proxkey-usb-token': {
      id: '/products/proxkey-usb-token'
      path: '/proxkey-usb-token'
      fullPath: '/products/proxkey-usb-token'
      preLoaderRoute: typeof ProductsProxkeyUsbTokenRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/mtoken-usb-token': {
      id: '/products/mtoken-usb-token'
      path: '/mtoken-usb-token'
      fullPath: '/products/mtoken-usb-token'
      preLoaderRoute: typeof ProductsMtokenUsbTokenRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/foreign-national-dsc': {
      id: '/products/foreign-national-dsc'
      path: '/foreign-national-dsc'
      fullPath: '/products/foreign-national-dsc'
      preLoaderRoute: typeof ProductsForeignNationalDscRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/epass-2003-usb-token': {
      id: '/products/epass-2003-usb-token'
      path: '/epass-2003-usb-token'
      fullPath: '/products/epass-2003-usb-token'
      preLoaderRoute: typeof ProductsEpass2003UsbTokenRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/dgft-dsc': {
      id: '/products/dgft-dsc'
      path: '/dgft-dsc'
      fullPath: '/products/dgft-dsc'
      preLoaderRoute: typeof ProductsDgftDscRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/class-3-organization-dsc': {
      id: '/products/class-3-organization-dsc'
      path: '/class-3-organization-dsc'
      fullPath: '/products/class-3-organization-dsc'
      preLoaderRoute: typeof ProductsClass3OrganizationDscRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/class-3-individual-dsc': {
      id: '/products/class-3-individual-dsc'
      path: '/class-3-individual-dsc'
      fullPath: '/products/class-3-individual-dsc'
      preLoaderRoute: typeof ProductsClass3IndividualDscRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/class-3-combo-dsc': {
      id: '/products/class-3-combo-dsc'
      path: '/class-3-combo-dsc'
      fullPath: '/products/class-3-combo-dsc'
      preLoaderRoute: typeof ProductsClass3ComboDscRouteImport
      parentRoute: typeof ProductsRoute
    }
  }
}

interface ProductsRouteChildren {
  ProductsClass3ComboDscRoute: typeof ProductsClass3ComboDscRoute
  ProductsClass3IndividualDscRoute: typeof ProductsClass3IndividualDscRoute
  ProductsClass3OrganizationDscRoute: typeof ProductsClass3OrganizationDscRoute
  ProductsDgftDscRoute: typeof ProductsDgftDscRoute
  ProductsEpass2003UsbTokenRoute: typeof ProductsEpass2003UsbTokenRoute
  ProductsForeignNationalDscRoute: typeof ProductsForeignNationalDscRoute
  ProductsMtokenUsbTokenRoute: typeof ProductsMtokenUsbTokenRoute
  ProductsProxkeyUsbTokenRoute: typeof ProductsProxkeyUsbTokenRoute
  ProductsSafenet5100UsbTokenRoute: typeof ProductsSafenet5100UsbTokenRoute
  ProductsTrustkeyUsbTokenRoute: typeof ProductsTrustkeyUsbTokenRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsClass3ComboDscRoute: ProductsClass3ComboDscRoute,
  ProductsClass3IndividualDscRoute: ProductsClass3IndividualDscRoute,
  ProductsClass3OrganizationDscRoute: ProductsClass3OrganizationDscRoute,
  ProductsDgftDscRoute: ProductsDgftDscRoute,
  ProductsEpass2003UsbTokenRoute: ProductsEpass2003UsbTokenRoute,
  ProductsForeignNationalDscRoute: ProductsForeignNationalDscRoute,
  ProductsMtokenUsbTokenRoute: ProductsMtokenUsbTokenRoute,
  ProductsProxkeyUsbTokenRoute: ProductsProxkeyUsbTokenRoute,
  ProductsSafenet5100UsbTokenRoute: ProductsSafenet5100UsbTokenRoute,
  ProductsTrustkeyUsbTokenRoute: ProductsTrustkeyUsbTokenRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  DownloadsRoute: DownloadsRoute,
  PartnersRoute: PartnersRoute,
  PricingRoute: PricingRoute,
  ProductsRoute: ProductsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
